// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Uint8List opId({required List<int> op}) =>
    RustLib.instance.api.crateApiSpikeOpId(op: op);

bool verifyEd25519({
  required List<int> pk,
  required List<int> msg,
  required List<int> sig,
}) =>
    RustLib.instance.api.crateApiSpikeVerifyEd25519(pk: pk, msg: msg, sig: sig);

/// Demo only: signs with a caller-supplied seed. The kernel proper never sees a secret.
SpikeOp spikeSignOp({
  required List<int> seed,
  required String app,
  required BigInt hlcMillis,
  required int hlcCounter,
  required List<int> body,
}) => RustLib.instance.api.crateApiSpikeSpikeSignOp(
  seed: seed,
  app: app,
  hlcMillis: hlcMillis,
  hlcCounter: hlcCounter,
  body: body,
);

bool verifyOp({required List<int> signed}) =>
    RustLib.instance.api.crateApiSpikeVerifyOp(signed: signed);

class SpikeOp {
  final Uint8List signable;
  final Uint8List signed;
  final Uint8List id;
  final Uint8List device;
  final Uint8List sig;

  const SpikeOp({
    required this.signable,
    required this.signed,
    required this.id,
    required this.device,
    required this.sig,
  });

  @override
  int get hashCode =>
      signable.hashCode ^
      signed.hashCode ^
      id.hashCode ^
      device.hashCode ^
      sig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpikeOp &&
          runtimeType == other.runtimeType &&
          signable == other.signable &&
          signed == other.signed &&
          id == other.id &&
          device == other.device &&
          sig == other.sig;
}
