// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'kernel.freezed.dart';

/// Which device stored records belong to and whether it was wiped, without keys.
StoredInfo? storedInfo({required List<Record> records}) =>
    RustLib.instance.api.crateApiKernelStoredInfo(records: records);

/// WipedPush after a restart: a wiped device's own sealed ops and its Forgets'
/// past, read from its records without keys, for the relay.
List<SealedOp> sealedHandover({
  required List<Record> records,
  required Schema schema,
  required BigInt now,
}) => RustLib.instance.api.crateApiKernelSealedHandover(
  records: records,
  schema: schema,
  now: now,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HearthKernel>>
abstract class HearthKernel implements RustOpaqueInterface {
  /// See `Kernel::abandon`.
  void abandon();

  /// See `Kernel::accept`.
  Step accept({required List<int> offer, required BigInt now});

  /// See `Kernel::adopt_snapshot`.
  Step adoptSnapshot({
    required List<int> snapshot,
    required List<Uint8List> ops,
    required BigInt now,
  });

  /// See `Kernel::checkpoint`.
  Step checkpoint({required BigInt now});

  /// See `Kernel::compact`.
  Outcome compact({required BigInt now});

  /// See `Kernel::devices`.
  List<DeviceInfo> devices();

  /// See `Kernel::dismiss_review`.
  Outcome dismissReview({required List<int> key});

  /// See `Kernel::enroll_device`.
  Step enrollDevice({
    required List<int> device,
    required String label,
    required BigInt now,
  });

  /// See `Kernel::enroll_self`.
  Step enrollSelf({required String label, required BigInt now});

  /// See `Kernel::finish`.
  Step finish({required List<int> signature});

  /// See `Kernel::flush`.
  Outcome flush();

  /// See `Kernel::forget_device`.
  Step forgetDevice({required List<int> device, required BigInt now});

  /// See `Kernel::forget_self`.
  Step forgetSelf({required BigInt now});

  /// See `Kernel::handover`.
  Uint8List handover({required List<int> request, required BigInt now});

  /// See `Kernel::heads`.
  List<Uint8List> heads();

  /// See `Kernel::hello`.
  Uint8List hello({required BigInt now});

  /// See `Kernel::ingest`.
  Outcome ingest({required List<Uint8List> sealed, required BigInt now});

  /// See `Kernel::offer`.
  Uint8List offer({required List<int> request});

  /// See `Kernel::open`.
  static HearthKernel open({required OpenArgs args}) =>
      RustLib.instance.api.crateApiKernelHearthKernelOpen(args: args);

  /// See `Kernel::relay_enrollment`.
  RelayEnrollment relayEnrollment({required List<int> device});

  /// See `Kernel::relay_forget_posted`.
  Outcome relayForgetPosted({required List<int> forget});

  /// See `Kernel::relay_forgets`.
  List<RelayForget> relayForgets();

  /// See `Kernel::relay_generation`.
  Outcome relayGeneration({required BigInt generation});

  /// See `Kernel::relay_outbox`.
  List<SealedOp> relayOutbox();

  /// See `Kernel::relay_pulled`.
  Outcome relayPulled({required List<RelayCursor> cursors});

  /// See `Kernel::relay_snapshot`.
  RelaySnapshot? relaySnapshot();

  /// See `Kernel::relay_state`.
  RelayState relayState();

  /// See `Kernel::relay_uploaded`.
  Outcome relayUploaded({
    required List<Uint8List> ids,
    required BigInt firstSeq,
  });

  /// See `Kernel::request`.
  RequestOut request({required List<int> hello});

  /// See `Kernel::review`.
  List<ReviewEntry> review();

  /// See `Kernel::snapshot`.
  Uint8List? snapshot();

  /// See `Kernel::status`.
  Status status();

  /// See `Kernel::view_all`.
  ViewDump viewAll();

  /// See `Kernel::write`.
  Step write({required Write write, required BigInt now});
}

@freezed
sealed class ApiError with _$ApiError implements FrbException {
  const ApiError._();

  const factory ApiError.badArgument(String field0) = ApiError_BadArgument;
  const factory ApiError.schema(String field0) = ApiError_Schema;
  const factory ApiError.undeclared() = ApiError_Undeclared;
  const factory ApiError.persist(String field0) = ApiError_Persist;
  const factory ApiError.badMessage() = ApiError_BadMessage;
  const factory ApiError.noKeys() = ApiError_NoKeys;
  const factory ApiError.clockBehind({
    required BigInt now,
    required BigInt latest,
  }) = ApiError_ClockBehind;
  const factory ApiError.rejected(String field0) = ApiError_Rejected;
  const factory ApiError.badSnapshot(String field0) = ApiError_BadSnapshot;
  const factory ApiError.snapshotUnavailable() = ApiError_SnapshotUnavailable;
  const factory ApiError.badSignature() = ApiError_BadSignature;
  const factory ApiError.nothingToFinish() = ApiError_NothingToFinish;
  const factory ApiError.awaitingSignature() = ApiError_AwaitingSignature;
}

class Collection {
  final String name;
  final Merge merge;

  const Collection({required this.name, required this.merge});

  @override
  int get hashCode => name.hashCode ^ merge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Collection &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          merge == other.merge;
}

class ContainerDef {
  final String field;
  final String table;

  const ContainerDef({required this.field, required this.table});

  @override
  int get hashCode => field.hashCode ^ table.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContainerDef &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          table == other.table;
}

class DeviceInfo {
  final Uint8List device;
  final String label;
  final bool forgotten;
  final bool me;

  const DeviceInfo({
    required this.device,
    required this.label,
    required this.forgotten,
    required this.me,
  });

  @override
  int get hashCode =>
      device.hashCode ^ label.hashCode ^ forgotten.hashCode ^ me.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          label == other.label &&
          forgotten == other.forgotten &&
          me == other.me;
}

class Field {
  final String name;
  final KernelValue value;

  const Field({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Field &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class FieldDef {
  final String name;
  final ValueType ty;
  final bool nullable;

  const FieldDef({
    required this.name,
    required this.ty,
    required this.nullable,
  });

  @override
  int get hashCode => name.hashCode ^ ty.hashCode ^ nullable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          ty == other.ty &&
          nullable == other.nullable;
}

@freezed
sealed class KernelValue with _$KernelValue {
  const KernelValue._();

  const factory KernelValue.null_() = KernelValue_Null;
  const factory KernelValue.bool(bool field0) = KernelValue_Bool;
  const factory KernelValue.int(PlatformInt64 field0) = KernelValue_Int;
  const factory KernelValue.text(String field0) = KernelValue_Text;
  const factory KernelValue.bytes(Uint8List field0) = KernelValue_Bytes;
}

@freezed
sealed class Merge with _$Merge {
  const Merge._();

  const factory Merge.lww({
    required List<FieldDef> fields,
    ContainerDef? container,
  }) = Merge_Lww;
  const factory Merge.addWinsSet({required ValueType element}) =
      Merge_AddWinsSet;
  const factory Merge.appendOnly({required ValueType record}) =
      Merge_AppendOnly;
}

class OpenArgs {
  final String app;
  final Uint8List seed;
  final Uint8List device;
  final Schema schema;
  final List<Record> records;
  final BigInt now;

  const OpenArgs({
    required this.app,
    required this.seed,
    required this.device,
    required this.schema,
    required this.records,
    required this.now,
  });

  @override
  int get hashCode =>
      app.hashCode ^
      seed.hashCode ^
      device.hashCode ^
      schema.hashCode ^
      records.hashCode ^
      now.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenArgs &&
          runtimeType == other.runtimeType &&
          app == other.app &&
          seed == other.seed &&
          device == other.device &&
          schema == other.schema &&
          records == other.records &&
          now == other.now;
}

class Outcome {
  final List<Record> records;
  final bool resetRecords;
  final List<RowChange> rows;
  final List<SetChange> sets;
  final List<StreamChange> streams;
  final List<SealedOp> outgoing;
  final List<Uint8List> heads;
  final List<Uint8List> delivered;
  final List<Uint8List> excluded;
  final List<Uint8List> quarantined;
  final List<Uint8List> held;
  final List<Uint8List> pending;
  final List<Rejection> rejected;
  final bool wiped;
  final List<Reissue> reissued;
  final bool replaceView;
  final List<ReviewEntry> reviewAdded;

  const Outcome({
    required this.records,
    required this.resetRecords,
    required this.rows,
    required this.sets,
    required this.streams,
    required this.outgoing,
    required this.heads,
    required this.delivered,
    required this.excluded,
    required this.quarantined,
    required this.held,
    required this.pending,
    required this.rejected,
    required this.wiped,
    required this.reissued,
    required this.replaceView,
    required this.reviewAdded,
  });

  @override
  int get hashCode =>
      records.hashCode ^
      resetRecords.hashCode ^
      rows.hashCode ^
      sets.hashCode ^
      streams.hashCode ^
      outgoing.hashCode ^
      heads.hashCode ^
      delivered.hashCode ^
      excluded.hashCode ^
      quarantined.hashCode ^
      held.hashCode ^
      pending.hashCode ^
      rejected.hashCode ^
      wiped.hashCode ^
      reissued.hashCode ^
      replaceView.hashCode ^
      reviewAdded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Outcome &&
          runtimeType == other.runtimeType &&
          records == other.records &&
          resetRecords == other.resetRecords &&
          rows == other.rows &&
          sets == other.sets &&
          streams == other.streams &&
          outgoing == other.outgoing &&
          heads == other.heads &&
          delivered == other.delivered &&
          excluded == other.excluded &&
          quarantined == other.quarantined &&
          held == other.held &&
          pending == other.pending &&
          rejected == other.rejected &&
          wiped == other.wiped &&
          reissued == other.reissued &&
          replaceView == other.replaceView &&
          reviewAdded == other.reviewAdded;
}

class Record {
  final Uint8List key;
  final Uint8List? value;

  const Record({required this.key, this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Record &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class Reissue {
  final Uint8List old;
  final Uint8List new_;

  const Reissue({required this.old, required this.new_});

  @override
  int get hashCode => old.hashCode ^ new_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Reissue &&
          runtimeType == other.runtimeType &&
          old == other.old &&
          new_ == other.new_;
}

class Rejection {
  final Uint8List id;
  final String code;

  const Rejection({required this.id, required this.code});

  @override
  int get hashCode => id.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rejection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          code == other.code;
}

class RelayCursor {
  final Uint8List device;
  final BigInt seq;

  const RelayCursor({required this.device, required this.seq});

  @override
  int get hashCode => device.hashCode ^ seq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayCursor &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          seq == other.seq;
}

class RelayEnrollment {
  final Uint8List household;
  final Uint8List device;
  final String label;
  final Uint8List auth;

  const RelayEnrollment({
    required this.household,
    required this.device,
    required this.label,
    required this.auth,
  });

  @override
  int get hashCode =>
      household.hashCode ^ device.hashCode ^ label.hashCode ^ auth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayEnrollment &&
          runtimeType == other.runtimeType &&
          household == other.household &&
          device == other.device &&
          label == other.label &&
          auth == other.auth;
}

class RelayForget {
  final Uint8List forget;
  final Uint8List target;
  final List<Uint8List> cut;
  final Uint8List auth;
  final BigInt cutSeq;

  const RelayForget({
    required this.forget,
    required this.target,
    required this.cut,
    required this.auth,
    required this.cutSeq,
  });

  @override
  int get hashCode =>
      forget.hashCode ^
      target.hashCode ^
      cut.hashCode ^
      auth.hashCode ^
      cutSeq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayForget &&
          runtimeType == other.runtimeType &&
          forget == other.forget &&
          target == other.target &&
          cut == other.cut &&
          auth == other.auth &&
          cutSeq == other.cutSeq;
}

class RelaySnapshot {
  final Uint8List sealed;
  final List<RelayCursor> covers;

  const RelaySnapshot({required this.sealed, required this.covers});

  @override
  int get hashCode => sealed.hashCode ^ covers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelaySnapshot &&
          runtimeType == other.runtimeType &&
          sealed == other.sealed &&
          covers == other.covers;
}

class RelayState {
  final BigInt generation;
  final BigInt nextSeq;
  final List<RelayCursor> cursors;

  const RelayState({
    required this.generation,
    required this.nextSeq,
    required this.cursors,
  });

  @override
  int get hashCode => generation.hashCode ^ nextSeq.hashCode ^ cursors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelayState &&
          runtimeType == other.runtimeType &&
          generation == other.generation &&
          nextSeq == other.nextSeq &&
          cursors == other.cursors;
}

class RequestOut {
  final Uint8List message;
  final bool needsSnapshot;

  const RequestOut({required this.message, required this.needsSnapshot});

  @override
  int get hashCode => message.hashCode ^ needsSnapshot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestOut &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          needsSnapshot == other.needsSnapshot;
}

class ReviewEntry {
  final Uint8List key;
  final String kind;
  final Uint8List op;
  final String opKind;
  final Uint8List? device;
  final String? table;
  final String? row;
  final String? field;
  final KernelValue? mine;
  final KernelValue? current;
  final String? set_;
  final String? stream;
  final Uint8List? enrolled;

  const ReviewEntry({
    required this.key,
    required this.kind,
    required this.op,
    required this.opKind,
    this.device,
    this.table,
    this.row,
    this.field,
    this.mine,
    this.current,
    this.set_,
    this.stream,
    this.enrolled,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      kind.hashCode ^
      op.hashCode ^
      opKind.hashCode ^
      device.hashCode ^
      table.hashCode ^
      row.hashCode ^
      field.hashCode ^
      mine.hashCode ^
      current.hashCode ^
      set_.hashCode ^
      stream.hashCode ^
      enrolled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReviewEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          kind == other.kind &&
          op == other.op &&
          opKind == other.opKind &&
          device == other.device &&
          table == other.table &&
          row == other.row &&
          field == other.field &&
          mine == other.mine &&
          current == other.current &&
          set_ == other.set_ &&
          stream == other.stream &&
          enrolled == other.enrolled;
}

class RowChange {
  final String table;
  final String row;
  final bool visible;
  final List<Field> fields;

  const RowChange({
    required this.table,
    required this.row,
    required this.visible,
    required this.fields,
  });

  @override
  int get hashCode =>
      table.hashCode ^ row.hashCode ^ visible.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RowChange &&
          runtimeType == other.runtimeType &&
          table == other.table &&
          row == other.row &&
          visible == other.visible &&
          fields == other.fields;
}

class Schema {
  final List<Collection> collections;
  final BigInt horizonMs;
  final bool keepFullHistory;

  const Schema({
    required this.collections,
    required this.horizonMs,
    required this.keepFullHistory,
  });

  @override
  int get hashCode =>
      collections.hashCode ^ horizonMs.hashCode ^ keepFullHistory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Schema &&
          runtimeType == other.runtimeType &&
          collections == other.collections &&
          horizonMs == other.horizonMs &&
          keepFullHistory == other.keepFullHistory;
}

class SealedOp {
  final Uint8List id;
  final Uint8List sealed;

  const SealedOp({required this.id, required this.sealed});

  @override
  int get hashCode => id.hashCode ^ sealed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SealedOp &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sealed == other.sealed;
}

class SetChange {
  final String set_;
  final KernelValue element;
  final bool present;

  const SetChange({
    required this.set_,
    required this.element,
    required this.present,
  });

  @override
  int get hashCode => set_.hashCode ^ element.hashCode ^ present.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetChange &&
          runtimeType == other.runtimeType &&
          set_ == other.set_ &&
          element == other.element &&
          present == other.present;
}

class Status {
  final Uint8List? device;
  final bool wiped;
  final bool enrolled;
  final BigInt pending;
  final BigInt quarantined;
  final BigInt held;
  final BigInt rejected;
  final bool schemaChanged;
  final bool awaitingSignature;

  const Status({
    this.device,
    required this.wiped,
    required this.enrolled,
    required this.pending,
    required this.quarantined,
    required this.held,
    required this.rejected,
    required this.schemaChanged,
    required this.awaitingSignature,
  });

  @override
  int get hashCode =>
      device.hashCode ^
      wiped.hashCode ^
      enrolled.hashCode ^
      pending.hashCode ^
      quarantined.hashCode ^
      held.hashCode ^
      rejected.hashCode ^
      schemaChanged.hashCode ^
      awaitingSignature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Status &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          wiped == other.wiped &&
          enrolled == other.enrolled &&
          pending == other.pending &&
          quarantined == other.quarantined &&
          held == other.held &&
          rejected == other.rejected &&
          schemaChanged == other.schemaChanged &&
          awaitingSignature == other.awaitingSignature;
}

@freezed
sealed class Step with _$Step {
  const Step._();

  const factory Step.sign({required Uint8List signable}) = Step_Sign;
  const factory Step.done(Outcome field0) = Step_Done;
}

class StoredInfo {
  final Uint8List? device;
  final bool wiped;

  const StoredInfo({this.device, required this.wiped});

  @override
  int get hashCode => device.hashCode ^ wiped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredInfo &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          wiped == other.wiped;
}

class StreamChange {
  final String stream;
  final Uint8List id;
  final BigInt millis;
  final int counter;
  final Uint8List device;
  final KernelValue record;
  final bool present;

  const StreamChange({
    required this.stream,
    required this.id,
    required this.millis,
    required this.counter,
    required this.device,
    required this.record,
    required this.present,
  });

  @override
  int get hashCode =>
      stream.hashCode ^
      id.hashCode ^
      millis.hashCode ^
      counter.hashCode ^
      device.hashCode ^
      record.hashCode ^
      present.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamChange &&
          runtimeType == other.runtimeType &&
          stream == other.stream &&
          id == other.id &&
          millis == other.millis &&
          counter == other.counter &&
          device == other.device &&
          record == other.record &&
          present == other.present;
}

enum ValueType { text, int, bool, bytes, any }

class ViewDump {
  final List<RowChange> rows;
  final List<SetChange> sets;
  final List<StreamChange> streams;

  const ViewDump({
    required this.rows,
    required this.sets,
    required this.streams,
  });

  @override
  int get hashCode => rows.hashCode ^ sets.hashCode ^ streams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewDump &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          sets == other.sets &&
          streams == other.streams;
}

@freezed
sealed class Write with _$Write {
  const Write._();

  const factory Write.put({
    required String table,
    required String row,
    required List<Field> fields,
  }) = Write_Put;
  const factory Write.delete({required String table, required String row}) =
      Write_Delete;
  const factory Write.restore({required String table, required String row}) =
      Write_Restore;
  const factory Write.setAdd({
    required String set_,
    required KernelValue element,
  }) = Write_SetAdd;
  const factory Write.setRemove({
    required String set_,
    required KernelValue element,
  }) = Write_SetRemove;
  const factory Write.append({
    required String stream,
    required KernelValue record,
  }) = Write_Append;
}
