// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'kernel.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `signer`

/// The Ed25519 public key (32 bytes) of a 32-byte seed.
Uint8List ed25519PublicKey({required List<int> seed}) =>
    RustLib.instance.api.crateApiSigningEd25519PublicKey(seed: seed);

/// An Ed25519 signature (64 bytes, RFC 8032, deterministic) over `message`.
Uint8List ed25519Sign({required List<int> seed, required List<int> message}) =>
    RustLib.instance.api.crateApiSigningEd25519Sign(
      seed: seed,
      message: message,
    );
