// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/kernel.dart';
import 'api/signing.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HearthKernelPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel;

  @protected
  HearthKernel
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    dynamic raw,
  );

  @protected
  HearthKernel
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    dynamic raw,
  );

  @protected
  HearthKernel
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    dynamic raw,
  );

  @protected
  HearthKernel
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiError dco_decode_api_error(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ContainerDef dco_decode_box_autoadd_container_def(dynamic raw);

  @protected
  KernelValue dco_decode_box_autoadd_kernel_value(dynamic raw);

  @protected
  OpenArgs dco_decode_box_autoadd_open_args(dynamic raw);

  @protected
  Outcome dco_decode_box_autoadd_outcome(dynamic raw);

  @protected
  RelaySnapshot dco_decode_box_autoadd_relay_snapshot(dynamic raw);

  @protected
  Schema dco_decode_box_autoadd_schema(dynamic raw);

  @protected
  StoredInfo dco_decode_box_autoadd_stored_info(dynamic raw);

  @protected
  Write dco_decode_box_autoadd_write(dynamic raw);

  @protected
  Collection dco_decode_collection(dynamic raw);

  @protected
  ContainerDef dco_decode_container_def(dynamic raw);

  @protected
  DeviceInfo dco_decode_device_info(dynamic raw);

  @protected
  Field dco_decode_field(dynamic raw);

  @protected
  FieldDef dco_decode_field_def(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KernelValue dco_decode_kernel_value(dynamic raw);

  @protected
  List<Collection> dco_decode_list_collection(dynamic raw);

  @protected
  List<DeviceInfo> dco_decode_list_device_info(dynamic raw);

  @protected
  List<Field> dco_decode_list_field(dynamic raw);

  @protected
  List<FieldDef> dco_decode_list_field_def(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Record> dco_decode_list_record(dynamic raw);

  @protected
  List<Reissue> dco_decode_list_reissue(dynamic raw);

  @protected
  List<Rejection> dco_decode_list_rejection(dynamic raw);

  @protected
  List<RelayCursor> dco_decode_list_relay_cursor(dynamic raw);

  @protected
  List<RelayForget> dco_decode_list_relay_forget(dynamic raw);

  @protected
  List<ReviewEntry> dco_decode_list_review_entry(dynamic raw);

  @protected
  List<RowChange> dco_decode_list_row_change(dynamic raw);

  @protected
  List<SealedOp> dco_decode_list_sealed_op(dynamic raw);

  @protected
  List<SetChange> dco_decode_list_set_change(dynamic raw);

  @protected
  List<StreamChange> dco_decode_list_stream_change(dynamic raw);

  @protected
  Merge dco_decode_merge(dynamic raw);

  @protected
  OpenArgs dco_decode_open_args(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ContainerDef? dco_decode_opt_box_autoadd_container_def(dynamic raw);

  @protected
  KernelValue? dco_decode_opt_box_autoadd_kernel_value(dynamic raw);

  @protected
  RelaySnapshot? dco_decode_opt_box_autoadd_relay_snapshot(dynamic raw);

  @protected
  StoredInfo? dco_decode_opt_box_autoadd_stored_info(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Outcome dco_decode_outcome(dynamic raw);

  @protected
  Record dco_decode_record(dynamic raw);

  @protected
  Reissue dco_decode_reissue(dynamic raw);

  @protected
  Rejection dco_decode_rejection(dynamic raw);

  @protected
  RelayCursor dco_decode_relay_cursor(dynamic raw);

  @protected
  RelayEnrollment dco_decode_relay_enrollment(dynamic raw);

  @protected
  RelayForget dco_decode_relay_forget(dynamic raw);

  @protected
  RelaySnapshot dco_decode_relay_snapshot(dynamic raw);

  @protected
  RelayState dco_decode_relay_state(dynamic raw);

  @protected
  RequestOut dco_decode_request_out(dynamic raw);

  @protected
  ReviewEntry dco_decode_review_entry(dynamic raw);

  @protected
  RowChange dco_decode_row_change(dynamic raw);

  @protected
  Schema dco_decode_schema(dynamic raw);

  @protected
  SealedOp dco_decode_sealed_op(dynamic raw);

  @protected
  SetChange dco_decode_set_change(dynamic raw);

  @protected
  Status dco_decode_status(dynamic raw);

  @protected
  Step dco_decode_step(dynamic raw);

  @protected
  StoredInfo dco_decode_stored_info(dynamic raw);

  @protected
  StreamChange dco_decode_stream_change(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ValueType dco_decode_value_type(dynamic raw);

  @protected
  ViewDump dco_decode_view_dump(dynamic raw);

  @protected
  Write dco_decode_write(dynamic raw);

  @protected
  HearthKernel
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    SseDeserializer deserializer,
  );

  @protected
  HearthKernel
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    SseDeserializer deserializer,
  );

  @protected
  HearthKernel
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    SseDeserializer deserializer,
  );

  @protected
  HearthKernel
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ContainerDef sse_decode_box_autoadd_container_def(
    SseDeserializer deserializer,
  );

  @protected
  KernelValue sse_decode_box_autoadd_kernel_value(SseDeserializer deserializer);

  @protected
  OpenArgs sse_decode_box_autoadd_open_args(SseDeserializer deserializer);

  @protected
  Outcome sse_decode_box_autoadd_outcome(SseDeserializer deserializer);

  @protected
  RelaySnapshot sse_decode_box_autoadd_relay_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  Schema sse_decode_box_autoadd_schema(SseDeserializer deserializer);

  @protected
  StoredInfo sse_decode_box_autoadd_stored_info(SseDeserializer deserializer);

  @protected
  Write sse_decode_box_autoadd_write(SseDeserializer deserializer);

  @protected
  Collection sse_decode_collection(SseDeserializer deserializer);

  @protected
  ContainerDef sse_decode_container_def(SseDeserializer deserializer);

  @protected
  DeviceInfo sse_decode_device_info(SseDeserializer deserializer);

  @protected
  Field sse_decode_field(SseDeserializer deserializer);

  @protected
  FieldDef sse_decode_field_def(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KernelValue sse_decode_kernel_value(SseDeserializer deserializer);

  @protected
  List<Collection> sse_decode_list_collection(SseDeserializer deserializer);

  @protected
  List<DeviceInfo> sse_decode_list_device_info(SseDeserializer deserializer);

  @protected
  List<Field> sse_decode_list_field(SseDeserializer deserializer);

  @protected
  List<FieldDef> sse_decode_list_field_def(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Record> sse_decode_list_record(SseDeserializer deserializer);

  @protected
  List<Reissue> sse_decode_list_reissue(SseDeserializer deserializer);

  @protected
  List<Rejection> sse_decode_list_rejection(SseDeserializer deserializer);

  @protected
  List<RelayCursor> sse_decode_list_relay_cursor(SseDeserializer deserializer);

  @protected
  List<RelayForget> sse_decode_list_relay_forget(SseDeserializer deserializer);

  @protected
  List<ReviewEntry> sse_decode_list_review_entry(SseDeserializer deserializer);

  @protected
  List<RowChange> sse_decode_list_row_change(SseDeserializer deserializer);

  @protected
  List<SealedOp> sse_decode_list_sealed_op(SseDeserializer deserializer);

  @protected
  List<SetChange> sse_decode_list_set_change(SseDeserializer deserializer);

  @protected
  List<StreamChange> sse_decode_list_stream_change(
    SseDeserializer deserializer,
  );

  @protected
  Merge sse_decode_merge(SseDeserializer deserializer);

  @protected
  OpenArgs sse_decode_open_args(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ContainerDef? sse_decode_opt_box_autoadd_container_def(
    SseDeserializer deserializer,
  );

  @protected
  KernelValue? sse_decode_opt_box_autoadd_kernel_value(
    SseDeserializer deserializer,
  );

  @protected
  RelaySnapshot? sse_decode_opt_box_autoadd_relay_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  StoredInfo? sse_decode_opt_box_autoadd_stored_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Outcome sse_decode_outcome(SseDeserializer deserializer);

  @protected
  Record sse_decode_record(SseDeserializer deserializer);

  @protected
  Reissue sse_decode_reissue(SseDeserializer deserializer);

  @protected
  Rejection sse_decode_rejection(SseDeserializer deserializer);

  @protected
  RelayCursor sse_decode_relay_cursor(SseDeserializer deserializer);

  @protected
  RelayEnrollment sse_decode_relay_enrollment(SseDeserializer deserializer);

  @protected
  RelayForget sse_decode_relay_forget(SseDeserializer deserializer);

  @protected
  RelaySnapshot sse_decode_relay_snapshot(SseDeserializer deserializer);

  @protected
  RelayState sse_decode_relay_state(SseDeserializer deserializer);

  @protected
  RequestOut sse_decode_request_out(SseDeserializer deserializer);

  @protected
  ReviewEntry sse_decode_review_entry(SseDeserializer deserializer);

  @protected
  RowChange sse_decode_row_change(SseDeserializer deserializer);

  @protected
  Schema sse_decode_schema(SseDeserializer deserializer);

  @protected
  SealedOp sse_decode_sealed_op(SseDeserializer deserializer);

  @protected
  SetChange sse_decode_set_change(SseDeserializer deserializer);

  @protected
  Status sse_decode_status(SseDeserializer deserializer);

  @protected
  Step sse_decode_step(SseDeserializer deserializer);

  @protected
  StoredInfo sse_decode_stored_info(SseDeserializer deserializer);

  @protected
  StreamChange sse_decode_stream_change(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ValueType sse_decode_value_type(SseDeserializer deserializer);

  @protected
  ViewDump sse_decode_view_dump(SseDeserializer deserializer);

  @protected
  Write sse_decode_write(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    HearthKernel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    HearthKernel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    HearthKernel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    HearthKernel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_container_def(
    ContainerDef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_kernel_value(
    KernelValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_open_args(
    OpenArgs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_outcome(Outcome self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_relay_snapshot(
    RelaySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_schema(Schema self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stored_info(
    StoredInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_write(Write self, SseSerializer serializer);

  @protected
  void sse_encode_collection(Collection self, SseSerializer serializer);

  @protected
  void sse_encode_container_def(ContainerDef self, SseSerializer serializer);

  @protected
  void sse_encode_device_info(DeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_field(Field self, SseSerializer serializer);

  @protected
  void sse_encode_field_def(FieldDef self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_kernel_value(KernelValue self, SseSerializer serializer);

  @protected
  void sse_encode_list_collection(
    List<Collection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_info(
    List<DeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field(List<Field> self, SseSerializer serializer);

  @protected
  void sse_encode_list_field_def(List<FieldDef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record(List<Record> self, SseSerializer serializer);

  @protected
  void sse_encode_list_reissue(List<Reissue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_rejection(
    List<Rejection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relay_cursor(
    List<RelayCursor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_relay_forget(
    List<RelayForget> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_review_entry(
    List<ReviewEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_row_change(
    List<RowChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sealed_op(List<SealedOp> self, SseSerializer serializer);

  @protected
  void sse_encode_list_set_change(
    List<SetChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stream_change(
    List<StreamChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_merge(Merge self, SseSerializer serializer);

  @protected
  void sse_encode_open_args(OpenArgs self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_container_def(
    ContainerDef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_kernel_value(
    KernelValue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_relay_snapshot(
    RelaySnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stored_info(
    StoredInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_outcome(Outcome self, SseSerializer serializer);

  @protected
  void sse_encode_record(Record self, SseSerializer serializer);

  @protected
  void sse_encode_reissue(Reissue self, SseSerializer serializer);

  @protected
  void sse_encode_rejection(Rejection self, SseSerializer serializer);

  @protected
  void sse_encode_relay_cursor(RelayCursor self, SseSerializer serializer);

  @protected
  void sse_encode_relay_enrollment(
    RelayEnrollment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_relay_forget(RelayForget self, SseSerializer serializer);

  @protected
  void sse_encode_relay_snapshot(RelaySnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_relay_state(RelayState self, SseSerializer serializer);

  @protected
  void sse_encode_request_out(RequestOut self, SseSerializer serializer);

  @protected
  void sse_encode_review_entry(ReviewEntry self, SseSerializer serializer);

  @protected
  void sse_encode_row_change(RowChange self, SseSerializer serializer);

  @protected
  void sse_encode_schema(Schema self, SseSerializer serializer);

  @protected
  void sse_encode_sealed_op(SealedOp self, SseSerializer serializer);

  @protected
  void sse_encode_set_change(SetChange self, SseSerializer serializer);

  @protected
  void sse_encode_status(Status self, SseSerializer serializer);

  @protected
  void sse_encode_step(Step self, SseSerializer serializer);

  @protected
  void sse_encode_stored_info(StoredInfo self, SseSerializer serializer);

  @protected
  void sse_encode_stream_change(StreamChange self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_value_type(ValueType self, SseSerializer serializer);

  @protected
  void sse_encode_view_dump(ViewDump self, SseSerializer serializer);

  @protected
  void sse_encode_write(Write self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHearthKernel(
    int ptr,
  );
}
